import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const gillSans = localFont({ src: '../fonts/GillSansNovaforJL-Medium.otf' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gillSans.className}>{children}</body>
    </html>
  );
}
